### ISSUE TITLE
webrtc.org/bugs/ works, but webrtc.org/bugs doesn't

### ISSUE THREAD

**Issue by juberti** [webrtc/webrtc-org#12]

**Comment by louquillio** [comment]
Answer here may be useful:

http://stackoverflow.com/questions/31637884/how-to-handle-trailing-slashing-in-google-app-engine-app-yaml

**Comment by x1ddos** [comment]
This is now fixed! Try it: https://webrtc.org/bugs

It's been fixed at the server level so no PRs are attached to this bug.

**Comment by KaptenJansson** [comment]
Do note that https://www.webrtc.org/native-code/android does not redirect to http://webrtc.org/native-code/android/ (I get a 500 error) while https://www.webrtc.org/native-code/android/ does (thanks @tednakamura for pointing this out).

**Comment by x1ddos** [comment]
Hm... strange. I'll make sure to fix this. Will keep this open until I do.
Thanks!

**Comment by x1ddos** [comment]
This was indeed a bug in the serving app where it would respond with incorrect `location` header.

The `location` was generated using a relative URL, e.g. `native-code/android` which, when resolved to the actual abs URL, would point the client to `/native-code/native-code/android/`.

This is now fixed.
