### ISSUE TITLE
Migrate to Travis CI

### ISSUE THREAD

**Issue by x1ddos** [webrtc/webrtc-org#130]
Creating this bug mostly for myself and also /cc @MirkoBonadei because we had a discussion about this in #116. I know it's been a crazy long time but I'm getting to it now. Better late than never.

**Comment by MirkoBonadei** [comment]
Awesome, thanks!

**Comment by x1ddos** [comment]
Hey @MirkoBonadei, I created a pull request and assigned you as a reviewer. Not sure github sends email notifications for this. Hope you don't mind.
