### ISSUE TITLE
Fix all broken links

### ISSUE THREAD

**Issue by x1ddos** [webrtc/webrtc-org#131]
Thanks to @MirkoBonadei suggestion, I ran html-proofer and it appears webrtc.org has quite a few broken links. Here are the commands I used:

    # build the website:
    bundle exec jekyll build --config _config.yml,_config_prod.yml

    # check broken links:
    gem install html-proofer
    htmlproofer ./_site --only-4xx --allow-hash-href --alt-ignore '/.*/'

And here's the output:

```
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] on ["./_site"] on *.html... 

Checking 379 external links...
Ran on 75 files!

- ./_site/blog/2012/03/05/source-code-to-apprtc.appspot.com-example-app-available.html
  *  External link https://chromium.googlesource.com/external/webrtc/+/master/talk/examples/android/src/org/appspot/apprtc failed: 404 No error
- ./_site/blog/2012/03/14/peerconnection-is-now-deprecatedpeerconnection.html
  *  External link http://code.google.com/p/webrtc-samples/source/browse/#svn%2Ftrunk%2Froap-jsep failed: 404 No error
- ./_site/debug/index.html
  *  External link https://github.com/louquillio/webrtc-site failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/10 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/11 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/12 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/13 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/14 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/15 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/16 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/17 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/2 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/4 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/5 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/6 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/7 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/8 failed: 404 No error
  *  External link https://github.com/louquillio/webrtc-site/issues/9 failed: 404 No error
  *  internally linking to /archive/, which does not exist (line 344)
     <a href="/archive/">archive</a>
- ./_site/faq/index.html
  *  External link https://chromium.googlesource.com/external/webrtc/+/master/webrtc/video_engine/include/vie_render.h failed: 404 No error
- ./_site/license/ilbc-freeware/ilbc-extra-documentation/index.html
  *  External link http://www.ilbcfreeware.org/documentation/ietf55-avt-duric.pdf failed: 404 No error
  *  External link http://www.ilbcfreeware.org/documentation/ietf56-avt-duric.pdf failed: 404 No error
- ./_site/native-code/android/index.html
  *  External link https://chromium.googlesource.com/external/webrtc/+/master/webrtc/api/java/README failed: 404 No error
- ./_site/native-code/native-apis/index.html
  *  External link https://chromium.googlesource.com/external/webrtc/+/master/webrtc/api/peerconnection.h failed: 404 No error
- ./_site/start/index.html
  *  External link http://auduno.github.io/clmtrackr/face_mask.html failed: 404 No error
  *  External link http://bit.ly/learnwebrtc failed: 404 No error
  *  External link http://hu.tt failed: 404 No error
  *  External link https://plus.sandbox.google.com/113817074606039822053/posts failed: 404 No error
- ./_site/testing/conformance/index.html
  *  External link http://build.chromium.org/p/chromium.webkit/builders/WebKit%20Linux%20%28dbg%29 failed: 404 No error
- ./_site/web-apis/index.html
  *  External link http://docs.webplatform.org/wiki/apis/webrtc failed: 404 No error
htmlproofer 3.6.0 | Error:  HTML-Proofer found 31 failures!
```

/cc @louquillio @samdutton

**Comment by louquillio** [comment]
My recent PRs resolve all but six stale link targets. The remainder *may* have valuable replacement targets that I'm unable to identify. Someone more knowledgeable should take a look. Remaining 404s:

~~~~~
- ./_site/faq/index.html
  *  External link https://chromium.googlesource.com/external/webrtc/+/master/webrtc/video_engine/include/vie_render.h failed: 404 No error

- ./_site/native-code/android/index.html
  *  External link https://chromium.googlesource.com/external/webrtc/+/master/webrtc/api/java/README failed: 404 No error

- ./_site/native-code/native-apis/index.html
  *  External link https://chromium.googlesource.com/external/webrtc/+/master/webrtc/api/peerconnection.h failed: 404 No error

- ./_site/start/index.html
  *  External link http://hu.tt failed: 404 No error
  *  External link https://plus.sandbox.google.com/113817074606039822053/posts failed: 404 No error

- ./_site/testing/conformance/index.html
  *  External link http://build.chromium.org/p/chromium.webkit/builders/WebKit%20Linux%20%28dbg%29 failed: 404 No error
~~~~~

**Comment by x1ddos** [comment]
Wow. This is awesome. Thanks @louquillio! I could try the first 3. For instance, `peerconnection.h` is here:  https://chromium.googlesource.com/external/webrtc/+/master/webrtc/pc/peerconnection.h

**Comment by MirkoBonadei** [comment]
Adding @hkjellander and @KaptenJansson for some hints on these links.

I am not 100% sure about `peerconnection.h`. It could also be https://chromium.googlesource.com/external/webrtc/+/master/webrtc/api/peerconnectioninterface.h.

The `/api/java/README` could be https://chromium.googlesource.com/external/webrtc/+/master/webrtc/sdk/android/README.

I have no ideas about: `vie_render.h`, http://hu.tt failed and https://plus.sandbox.google.com/113817074606039822053/posts, but I think we can remove them.

Also no idea about the `conformance` link.

**Comment by kjellander-unity** [comment]
Both the peerconnection.h and mediastream.h links should be replaced with: https://chromium.googlesource.com/external/webrtc/+/master/webrtc/api/peerconnectioninterface.h and https://chromium.googlesource.com/external/webrtc/+/master/webrtc/api/mediastreaminterface.h since we only want to point at public (and supported) APIs.

> /api/java/README could be https://chromium.googlesource.com/external/webrtc/+/master/webrtc/sdk/android/README.

That's correct

> vie_render.h

Remove; it was deleted back in https://webrtc-codereview.appspot.com/55379004

> hu.tt

Just remove, it seems to be some old name of a Citrix product (not sure what it might have been replaced with). https://news.ycombinator.com/item?id=6682853

> https://plus.sandbox.google.com/113817074606039822053/posts

Just remove if it can't be found. Dunno what it could have been.

> conformance page

The http://www.chromium.org/blink/importing-the-w3c-tests link should be replaced with https://chromium.googlesource.com/chromium/src/+/master/docs/testing/web_platform_tests.md
Let's just remove the outdated buildbot link entirely.

**Comment by MirkoBonadei** [comment]
Thanks @hkjellander. I will create a pull request to fix these links in a few minutes.

**Comment by MirkoBonadei** [comment]
I have just created the pull request: https://github.com/webrtc/webrtc-org/pull/136.

**Comment by x1ddos** [comment]
For some reason #139 disabled links check. Why?

**Comment by ilyanikolaevskiy** [comment]
x1ddos: because it was preventing from adding a new page to the site. It was somehow checking internal link to a new page before adding it.

Edit: it was more tricky - there was an absolute self-link to the newly added page. Because before pull request is merged, the new page was not published, this link was always broken.

**Comment by KaptenJansson** [comment]
any updates?

**Comment by ilyanikolaevskiy** [comment]
The link's proofer should be enabled by now. I enabled it here together with fixing some broken links: 
https://github.com/webrtc/webrtc-org/pull/143
