### ISSUE TITLE
Html-proofer should be reenabled.

### ISSUE THREAD

**Issue by ilyanikolaevskiy** [webrtc/webrtc-org#144]
Htmlproofer was disabled because of a tricky self-link at the rtp-hdrext page. It should be re-enabled back.
Currently there are some broken links preventing from doing that:

```
- ./_site/start/index.html
  *  External link https://protothon.com/blog/2012/mar/27/red-square-puzzle-group failed: 404 No error
htmlproofer 3.7.2 | Error:  HTML-Proofer found 1 failure!

```

**Comment by MirkoBonadei** [comment]
Thanks for the heads up. I will allocate some time this week to look into this.

**Comment by KaptenJansson** [comment]
ping

**Comment by ilyanikolaevskiy** [comment]
The link's proofer should be enabled by now. I enabled it here: 
https://github.com/webrtc/webrtc-org/pull/143
