### ISSUE TITLE
http://code.webrtc.org should point to https://chromium.googlesource.com/external/webrtc/+/master

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/webrtc-org#16]

**Comment by KaptenJansson** [comment]
It should point to our official code browsing site, I assume this is https://chromium.googlesource.com/external/webrtc/+/master for now.

**Comment by kjellander-unity** [comment]
Yes, that's a good idea. Right now it redirects to the issue tracker since I guess it's pointing at the old Google code site.

**Comment by samdutton** [comment]
@crhym3 — could you set this up?

**Comment by x1ddos** [comment]
I think so. Let me check internally the current setup...

**Comment by x1ddos** [comment]
Fixed it internally. The change should be visible in about couple hours.

**Comment by x1ddos** [comment]
This is now live. Try in incognito window if you don't see it yet, the browser might still have old redirect in cache.

As a bonus, the redirect also follows optional suffix. For instance, http://code.webrtc.org/README.md will go to https://chromium.googlesource.com/external/webrtc/+/master/README.md
