### ISSUE TITLE
Rename ICE to "ISE"

### ISSUE THREAD

**Issue by ghost** [webrtc/webrtc-org#178]
"ICE" is an organization that forces mexican immigrants outside the US thus might be triggering to persons of hispanic descent. It'd be much better if we renamed ICE to "ISE".

**Comment by alvestrand** [comment]
ICE (Interactive Connectivity Establishment, RFC 5245) is unfortunately also used for the name of a technology that is part of the WebRTC protocol suite. It will not change.
Sorry about that.
