### ISSUE TITLE
Invalid Code review and issue tracker URLs

### ISSUE THREAD

**Issue by kjellander-unity** [webrtc/webrtc-org#20]
As reported by tfarina@chromium.org; the code review server link in https://webrtc.org/contributing/ currently points to http://webrtc-codereview.appspot.com/, but should be https://codereview.webrtc.org.

And in https://webrtc.org/native-code/, the bug tracker link should be changed from https://code.google.com/p/webrtc/issues/list to https://bugs.chromium.org/p/webrtc/issues/list?

There are also several stale URLs to Chromium build instructions.

**Comment by KaptenJansson** [comment]
I believe you fixed the URL's in https://github.com/webrtc/webrtc-org/pull/21? If so please close this (Tip: If you add Fixes #bugnumber in the pull request it will auto close the bug).

**Comment by KaptenJansson** [comment]
Ooops :)

**Comment by kjellander-unity** [comment]
Ah yes, I was going to close this (forgot about it back then, just wanted to rush those fixes in).
I'll make sure to use the "Fixes #bugnumber" feature in the future.

**Comment by DanilChapovalov** [comment]
link from http://webrtc.org/native-code/ to issue tracker doesn't work: it redirects to google.com.
http://bugs.webrtc.org/ (same link without https) redirects correctly.

**Comment by KaptenJansson** [comment]
Well spotted, yeah redirects often do not work with HTTPS ;).

**Comment by x1ddos** [comment]
Hm... strange. I thought I'd fixed both bugs.webrtc.org and code.webrtc.org.
Let me check.

**Comment by x1ddos** [comment]
Apparently I forgot one bit. Sorry! Fixing it now...

**Comment by x1ddos** [comment]
I mean, don't change from `https` to `http`. The https version should start working soon.

**Comment by x1ddos** [comment]
The redirects should start working within a couple hours.

**Comment by x1ddos** [comment]
@DanilChapovalov both https://bugs.webrtc.org and https://code.webrtc.org work now. Thanks for noticing.
