### ISSUE TITLE
list of security issues is outdated

### ISSUE THREAD

**Issue by fippo** [webrtc/webrtc-org#204]
https://webrtc.org/bugs/security/ says
`(None so far)`

https://bugs.chromium.org/p/project-zero/issues/list?can=1&q=webrtc&colspec=ID+Status+Restrict+Reported+Vendor+Product+Finder+Summary&cells=ids shows seven.

**Comment by alvestrand** [comment]
... but they're all fixed?

**Comment by nils-ohlmeier** [comment]
So if I integrate webrtc.org into my product and want to know which problems were there and which affect my products, then I do what?

**Comment by nils-ohlmeier** [comment]
Or to put a different perspective on it: since the project zero bugs (most of the time) only get disclosed once they are fixed upstream the page will never list any open issues (which might be questionable any how). Wouldn't then be more honest to simply remove that page, instead of creating the illusion that webrtc.org is the safest project ever?

**Comment by fippo** [comment]
see also my questions from #195...

**Comment by natashenka** [comment]
I think removing this would be a good idea, as integrators might mistake that for a page they can monitor to be notified of security patched they need to apply.

**Comment by benjwright** [comment]
Fixed in: https://github.com/webrtc/webrtc-org/pull/229

**Comment by fippo** [comment]
No longer outdated indeed. I still think that it should not be that much effort to provide better guidance to users but seeing how long it took you to get this merged... :-|

**Comment by benjwright** [comment]
Security advisories are definitely lacking for external partners so I totally agree with you on #195 

I think we need to consider having a mailing list that is just for security advisories and automatically picks up and posts the chromium bugs once they are visible. The current timeline of 14 or so weeks is a long time so finding some balance here between meeting the needs of the chromium security policy and our external customers would be great.

Maybe we can move this over to a webrtc bug and continue the discussion there.
