### ISSUE TITLE
onBufferedAmountLow executes too late

### ISSUE THREAD

**Issue by MootCourt2018** [webrtc/webrtc-org#211]
When I am executing the send() - method on my dataChannel too often in a short period of time the message buffer flows over. I tried to fix this by stoping bthe execution on the onBufferedAmountLow event. But when the event is called the buffer is already full.

Is this a known problem or is there any workaround?

**Comment by lgrahl** [comment]
This isn't the repo for questions regarding the libwebrtc implementation. Please try [discuss-webrtc](http://groups.google.com/group/discuss-webrtc) next time. :slightly_smiling_face: 

Yes, there is a bug but I'm quite sure you have the wrong impression of the `bufferedamountlow` event. It fires when the buffer is (near) empty, not when it's full. See https://github.com/webrtc/samples/blob/410a2ecd1ba2938aab1310c519725f80ae03247d/src/content/datachannel/datatransfer/js/main.js for an example of how to use those events.

**Comment by fippo** [comment]
see also https://github.com/w3c/webrtc-pc/issues/1979 and the linked discussion.

**Comment by MootCourt2018** [comment]
Thanks for the help.

**Comment by alvestrand** [comment]
Closing as the question has been moved to a more appropriate repo.
