### ISSUE TITLE
Sync web page contents with the old site

### ISSUE THREAD

**Issue by kjellander-unity** [webrtc/webrtc-org#22]
Several pages are out of date when compared with the old site at https://sites.google.com/site/webrtc/.

@louquillio did you have a good way of syncing them, or is it just manual work? If so we should at least load-balance the work to get it synced up quickly.
I recall you kept a record on what changes were synced back when the new site was being developed. Maybe you can create a list of which changes needs to be synced?

**Comment by louquillio** [comment]
It's manual. I'll do it. Signed-in admins can see recent site activity:

https://sites.google.com/site/webrtc/system/app/pages/admin/recentsiteactivity

In the past I've used this view to identify the changes, but porting them is nevertheless manual.

**Comment by louquillio** [comment]
If PRs 25-31 are satisfactory, this can be closed.

**Comment by kjellander-unity** [comment]
They look good, thanks!

**Comment by kjellander-unity** [comment]
(I guess maybe we should wait closing until they're submitted)
