### ISSUE TITLE
outdated release branch information?

### ISSUE THREAD

**Issue by fippo** [webrtc/webrtc-org#241]
as of the change announced [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/JR7fsoEuqw0/zVRdTPEKBgAJ)
the information on the [native code development page](https://webrtc.org/native-code/development/)
is outdated, no? @anatolid: the email text looks pretty good.

**Comment by anatolid** [comment]
Hi @fippo! What information specifically on that page is outdated, in your opinion?

Not sure I understand your comment about 'email text'...
