### ISSUE TITLE
frame limitation 10ms error

### ISSUE THREAD

**Issue by Tortoise17** [webrtc/webrtc-org#248]
With this library, there is the frame limitation hardcoded of 10ms, 20ms, 30ms where as the minimum possible is only 10ms. Is there any way to make it like 1ms / 2ms / 3ms / 4ms / 5ms / 6ms 7ms / 8ms / 9ms  or so flexible or at least any reduced small possible frame? because this frame size has issues. Please help.

**Comment by alvestrand** [comment]
This bug tracker is only intended for issues with the webrtc.org web site.
Please use:

- bugs.webrtc.org if you believe there's a bug in WebRTC code
- crbug.com if you believe there's a bug in Chromium
- [discuss-webrtc@googlegroups.com](mailto:discuss-webrtc@googlegroups.com) for general questions aruond using WebRTC
