### ISSUE TITLE
[build webrtc for Windows x86] peerconnection_client crashed after setting is_clang =false 

### ISSUE THREAD

**Issue by Sleepingbug** [webrtc/webrtc-org#256]
OS: Win10 Pro 64-bit
VS: VS2017,

Build webrtc library for Windows x86.
when i set is_clang = true,
peerconnection_client.exe works well.

but set is_clang = false then
peerconnection_client.exe will crash.
command:
`gn gen out/x86/release_clang_flase --ide=vs2017 --args="is_debug=false rtc_include_tests=false target_cpu=\"x86\" symbol_level=0 gtest_enable_absl_printers=false is_clang=false"`

two or three seconds later after starting the video chat, peerconnection_client.exe crashed.
errors:
`peerconnection_client.exe!_vp8_fast_quantize_b_ssse3()	C
peerconnection_client.exe!_vp8_quantize_mby()	C
peerconnection_client.exe!_vp8_encode_intra16x16mby()	C
peerconnection_client.exe!_vp8cx_encode_inter_macroblock()	C
peerconnection_client.exe!_vp8_store_drop_frame_info()	C
peerconnection_client.exe!_vp8_encode_frame()	C
peerconnection_client.exe!_av1_write_uleb_obu_size()	C
peerconnection_client.exe!_vp8_get_compressed_data()	C
peerconnection_client.exe!webrtc::Vp8FrameConfig::Updates(enum webrtc::Vp8FrameConfig::Buffer)	C
peerconnection_client.exe!_vpx_codec_encode()	C
peerconnection_client.exe!webrtc::LibvpxInterface::CreateEncoder(void)	C++
peerconnection_client.exe!webrtc::LibvpxVp8Encoder::Encode(class webrtc::VideoFrame const &,class std::vector<enum webrtc::VideoFrameType,class std::allocator<enum webrtc::VideoFrameType> > const *)	C++
peerconnection_client.exe!webrtc::VideoStreamEncoder::EncodeVideoFrame(class webrtc::VideoFrame const &,__int64)	C++
peerconnection_client.exe!webrtc::VideoStreamEncoder::MaybeEncodeVideoFrame(class webrtc::VideoFrame const &,__int64)	C++
peerconnection_client.exe!webrtc::VideoStreamEncoder::EncoderRateSettings::operator!=(struct webrtc::VideoStreamEncoder::EncoderRateSettings const &)	C++
peerconnection_client.exe!webrtc::VideoStreamEncoder::ReleaseEncoder(void)	C++
peerconnection_client.exe!webrtc::CreateTaskQueueWinFactory(void)	C++
peerconnection_client.exe!webrtc::CreateTaskQueueWinFactory(void)	C++
peerconnection_client.exe!rtc::PlatformThread::Run(void)	C++
peerconnection_client.exe!rtc::PlatformThread::StartThread(void *)	C++
kernel32.dll!76f86359()	Unkown`

It seems that after setting is_clang = false, the vp8 encoding is wrong.
How to solve it?

**Comment by Sleepingbug** [comment]
it's a bug in VS2017 compiler. 
I've fixed it.

**Comment by ZWJ2001** [comment]
Hello, I also encountered the same problem, is this caused by the vs2017 compiler? How did you deal with it? Switch directly to vs2019 or another version of the compiler? Or can I continue to use the vs2017 compiler and just change something else? thank you.

**Comment by ZWJ2001** [comment]
If I don't change it, will it affect my own program in any way other than the official example running unsuccessfully?
