### ISSUE TITLE
Chromebook chromeos version 83.0.4103.97 chrome extension webrtc  audio to any peer So many noise

### ISSUE THREAD

**Issue by czq7966** [webrtc/webrtc-org#259]
While Chromebook ChromeOS Chrome version updated to new stable version 83.0.4103.97 from 81.xxx or lower，the sender auido got from chrome extension webrtc sound so many noise at the receiver peer on android or win or other system, just ChromeOS has this problem, others not. 
  And if a new tab page hold the microphone stream got by navigator.mediaDevices.getUserMedia({audio: true, video: false}) api，the noise problem disappear，and happen again while release the microphone stream or close the tab page.
  Any  sugestion?

 the chromium issue link: 
https://bugs.chromium.org/p/chromium/issues/detail?id=1094279

**Comment by alvestrand** [comment]
This bug tracker is only intended for issues with the webrtc.org web site.
Please use:

- bugs.webrtc.org if you believe there's a bug in WebRTC code
- crbug.com if you believe there's a bug in Chromium
- [discuss-webrtc@googlegroups.com](mailto:discuss-webrtc@googlegroups.com) for general questions aruond using WebRTC
