### ISSUE TITLE
WebRTC std::deque iterator exception while running peerconenction_client.exe debug verion

### ISSUE THREAD

**Issue by Sleepingbug** [webrtc/webrtc-org#260]
I compiled webrtc code and generated webrtc.lib and peerconnection_client.exe and peerconnection_server.exe, 
but I have a strange error when I run peerconnection_client.exe program in Windows x86 Debug configuration  on Visual Studio :

Error message:

C:\Program Files(x86)\Microsoft Visual Studio\2019\Professinal\VC\msvc\14.25.28610\include\deque 
line 279 

Expression:cannot increment value-initialized deque iterator

//////////////////

_Deque_const_iterator& operator++() {
        #if _ITERATOR_DEBUG_LEVEL != 0
            const auto _Mycont = static_cast<const _Mydeque*>(this->_Getcont());
            _STL_VERIFY(_Mycont, "cannot increment value-initialized deque iterator");
here---->   _STL_VERIFY(this->_Myoff < _Mycont->_Myoff + _Mycont->_Mysize, "cannot increment deque iterator past end");**
        #endif // _ITERATOR_DEBUG_LEVEL != 0

        ++_Myoff;
        return *this;
}

///////////

With the same configuration (except is_debug=false), the relase version runs well
`

**Comment by Sleepingbug** [comment]
I have tried many times, but the result is that the webrtc.lib debug version has problems and the release version is OK.

**Comment by alvestrand** [comment]
This bug tracker is only intended for issues with the webrtc.org web site.
Please use:

- bugs.webrtc.org if you believe there's a bug in WebRTC code
- crbug.com if you believe there's a bug in Chromium
- [discuss-webrtc@googlegroups.com](mailto:discuss-webrtc@googlegroups.com) for general questions aruond using WebRTC
