### ISSUE TITLE
Code block rendering in production

### ISSUE THREAD

**Issue by louquillio** [webrtc/webrtc-org#38]
Commit e6a9067 was intended to address code block syntax-highlighting in the updated GitHub Pages environment, which is phasing in Jekyll 3 and a requirement to use the Rouge highlighter. This works as intended in my local clone and my GitHub fork (example):

http://www.quillio.com/webrtc-org/native-code/android/

But it's not working in the production site:

https://webrtc.org/native-code/android/

My guess is that the production site is being generated with different versions of various gems than GH Pages now uses. @crhym3, could you take a look? The most convenient way to update my local env was to uninstall all gems and then reinstall the github-pages gem. Trying to update gems piecemeal sent me into dependency hell.

Thanks!

**Comment by x1ddos** [comment]
Hey @louquillio that's correct, the site is being generated with gem versions specified in [Gemfile.lock](https://github.com/webrtc/webrtc-org/blob/583fa9bc5d7e582e4486b287bce4fe4455141f85/Gemfile.lock#L31). In fact, the jekyll version we're currently using is `2.4.0`.

Let me fix that in a new pull request.
