### ISSUE TITLE
Removed pages still served at webrtc.org

### ISSUE THREAD

**Issue by kjellander-unity** [webrtc/webrtc-org#42]
I found that https://webrtc.org/reference/getting-started/ is still being served and shows outdated information (the page doesn't exist in the github repo).

@louquillio do we need to add a step to the deployment procedure to ensure cleanup when pages are removed/moved.

Related: I created pull request #41 for cleaning up that directory entirely.

**Comment by x1ddos** [comment]
@hkjellander yeah, the deployment process doesn't remove content, only adds/modifies.

Is it a big deal given the page is not linked from anywhere?
I you guys think it is, I'll add the functionality to remove deleted pages.

**Comment by louquillio** [comment]
@crhym3  I'd say it's essential. Similarly, a way to insert 301 redirects will inevitably be needed. Might it be done repo-side, perhaps with a bit of YAML, or is that feature bloat? Sometimes redirects are urgent. Thanks.

**Comment by x1ddos** [comment]
Redirects already work but not from a yaml. It is done at the GCS objects level.
But I could think of some config file -based redirects too.

I'll assign this issue to me meanwhile and start working on it.

**Comment by kjellander-unity** [comment]
We must make sure we get this fixed. Search engines and links we're unaware of still reference pages that sit in the reference/ location. Most recently a lot of time was wasted figuring out how to build in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/lMWK84G8oX4/4b7JoU7GLQAJ

**Comment by x1ddos** [comment]
We can also do redirects from removed pages to their
successors/replacements. Would that help as well? If so, what would a
redirects list look like?

**Comment by kjellander-unity** [comment]
For reference/\* I think it's fine to just wipe them all. It's reasonably easy to find the new instructions.

**Comment by x1ddos** [comment]
Ok. Sounds goos. I'll try to fix it tomorrow.

**Comment by kjellander-unity** [comment]
This is now fixed, thanks!
