### ISSUE TITLE
VP9 missing from documentation

### ISSUE THREAD

**Issue by samdutton** [webrtc/webrtc-org#43]
As per [bugs.chromium.org/p/webrtc/issues/detail?id=5560](https://bugs.chromium.org/p/webrtc/issues/detail?id=5560#):

> Reported by kayalew@google.com, Feb 19
> 
> At https://webrtc.org/architecture/ and https://webrtc.org/faq/ (and possibly others) I noticed that VP9 hadn't been mentioned. Looking at https://developers.google.com/web/updates/2016/01/vp9-webrtc it seems like WebRTC has VP9 support. This is a request to update the documentation with regards to VP9.
> 
> braveyao@webrtc.org, Today
> 
> VP9 is included without a flag since M48 and is not the default video codec yet. And the website should be updated accordingly.

**Comment by rantonysamy** [comment]
Partially fixed, Added in the FAQ.
