### ISSUE TITLE
Redirect HTTP to HTTPS?

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/webrtc-org#46]
Is there any reason why do not want to redirect to HTTPS for webrtc.org? I guess an DNS ISP redirect is best.

@crhym3 @samdutton @louquillio WDYT?

**Comment by samdutton** [comment]
SGTM.

**Comment by x1ddos** [comment]
No reason, really. I'll configure the redirect.

**Comment by KaptenJansson** [comment]
Cool stuff ;)

**Comment by KaptenJansson** [comment]
Ping

**Comment by x1ddos** [comment]
Thanks for the ping. I should be done it this week.

**Comment by x1ddos** [comment]
This is fixed by https://github.com/google/weasel/commit/60a25e5b1572f4c8651e9c096285da840ef19d7e

**Comment by x1ddos** [comment]
Sorry for keeping this open for so long.

**Comment by samdutton** [comment]
And as if by magic ;)...

Try this: http://simpl.info/gum.

**Comment by KaptenJansson** [comment]
Awesome, thanks!

**Comment by samdutton** [comment]
Oops... Replied to wrong email :/.

I was on a separate thread about simple.info defaulting to HTTPS.
On 20 Apr 2016 8:56 a.m., "Christoffer Jansson" notifications@github.com
wrote:

Awesome, thanks!

**Comment by samdutton** [comment]
...and (no thanks to auto-correct) that's simpl.info.
