### ISSUE TITLE
https://html5rocks.com/en/tutorials/webrtc/infrastructure/ results in 404 on http://webrtc.org/start/

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/webrtc-org#48]
https://html5rocks.com/en/tutorials/webrtc/infrastructure/ result in 404, i.e. it is not served over HTTPS.

@samdutton do you know if there are any plans on serving HTML5rocks over HTTPS anytime soon?

**Comment by samdutton** [comment]
#49 should fix this.

Sadly, no plan to serve HTML5 Rocks over HTTPS any time soon. Content is being moved to Web Fundamentals.
