### ISSUE TITLE
Prerequisites software link is dead on https://webrtc.org/reference/getting-started/

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/webrtc-org#55]
https://webrtc.org/reference/getting-started/prerequisite-sw/ gives a 404.

It looks like the path is correct in https://github.com/webrtc/webrtc-org/blame/gh-pages/native-code/development/index.md#L360.

@louquillio do you know what's going on?

**Comment by x1ddos** [comment]
Isn't this the page? https://webrtc.org/native-code/development/prerequisite-sw/

**Comment by KaptenJansson** [comment]
Yes it is but when you click the link it navigates to https://webrtc.org/reference/getting-started/prerequisite-sw/

**Comment by KaptenJansson** [comment]
Seems like the site base url gets confused somehow.

**Comment by x1ddos** [comment]
Sorry, where is the link? The one on https://webrtc.org/native-code/development/ looks fine to me:

![screenshot from 2016-04-06 10 33 30](https://cloud.githubusercontent.com/assets/25405/14312199/18aad1fe-fbe3-11e5-917c-ae728e82e1a1.png)

**Comment by KaptenJansson** [comment]
aha it breaks because I followed an old link in a [post](https://groups.google.com/d/msgid/discuss-webrtc/d7c6deee-bee1-45d1-99e4-ccfa8be62a81%40googlegroups.com?utm_medium=email&utm_source=footer) by a user.

If you navigate to https://webrtc.org/reference/getting-started/ and then click the link it's broken.

**Comment by x1ddos** [comment]
Stale /reference/\* pages are removed. I think this can be closed in favour of #42
